### PR TITLE
CharController Basic, Audio Manager, Input Script

### PR DESCRIPTION
**Pull request by TheTacBanana**

### CODE REVIEW

**Comment by TheTacBanana** [comment]
fine

**Review by TheTacBanana — COMMENTED** [review]
fine

**Review by akusan — APPROVED** [review]

**Comment by akusan** [comment]
Approved

**Review by akusan — APPROVED** [review]

**Review by akusan — APPROVED** [review]

**Review by akusan — APPROVED** [review]
approved

**Review by akusan — APPROVED** [review]
approved

**Review by FearlessClock — APPROVED** [review]

**Pull request merged**
